version: 2
project_name: kodkafa

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kodkafa-cli
    main: ./cmd/kodkafa/main.go
    binary: kodkafa
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    ldflags:
      - -X kodkafa/internal.Version={{.Version}}
      - -X kodkafa/internal.Commit={{.ShortCommit}}

  - id: kod-cli
    main: ./cmd/kod/main.go 
    binary: kod            
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    ldflags:
      - -X kodkafa/internal.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
    format_overrides:
      - goos: windows
        formats: [zip] 

# Yeni standart: homebrew_casks (v2.10+)
homebrew_casks:
  - name: kodkafa
    description: "A Persistent CLI for Your Scripts, With Memory"
    homepage: "https://kodkafa.com"
    repository:
      owner: kodkafa
      name: homebrew-tap

    binaries:
      - kod
      - kodkafa

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kod"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kodkafa"]
          end

    caveats: |
      KODKAFA is installed! You can use 'kod' or 'kodkafa' commands.
      If you face security issues on macOS, run:
      xattr -dr com.apple.quarantine $(which kodkafa)

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:"]

release:
  footer: "Released by [KODKAFA](https://github.com/kodkafa)."